# Generated by Django 5.1.7 on 2025-04-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
