# Generated by Django 5.1.7 on 2025-04-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntaje', models.DecimalField(decimal_places=0, max_digits=10)),
                ('duracion', models.DecimalField(decimal_places=0, max_digits=10)),
                ('genero', models.CharField(max_length=150)),
            ],
        ),
    ]
