# Generated by Django 5.1.7 on 2025-04-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pelicula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
