# Generated by Django 5.1.7 on 2025-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='edad',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
