# Generated by Django 5.1.7 on 2025-04-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pelicula_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
