# Generated by Django 5.1.7 on 2025-04-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pelicula_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
