# Generated by Django 5.1.7 on 2025-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pelicula_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(blank=True, default='boludo.jpg', null=True, upload_to=''),
        ),
    ]
